dbt_databaddies_project:
  target: raw
  outputs:
    raw:
      type: duckdb
      path: "md:Airbyte_Motherduck_Hackathon?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      threads: 2
    intermediate:
      type: duckdb
      path: "md:Airbyte_motherduck_hackathon?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      threads: 2
    core:
      type: duckdb
      path: "md:Airbyte_motherduck_hackathon?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      threads: 2